Done
the-csharp-academy/CodeReviews.Console.SportsResults pull request #18
Opened 2024-03-14 20:11 UTC by kronyer

2024-03-14 20:13 UTC, kronyer commented
Hey, i had no idea how to format the results and also had no idea what those basketballs points meant, I've never watched a single game in my life. So if i need to change something, just let me know

2024-03-28 17:36 UTC, kimfom01 requested changes
So sorry this project took forever to be reviewed :cry: but congratulations on completing it :confetti_ball: 

I have some changes I'd like you to address before I approve it. Best of luck!

2024-03-28 17:36 UTC, kimfom01 commented on SportsResultNotifier.kronyer/SportsResultNotifier/MailService.cs
> +                string smtpAddress = "smtp.gmail.com";
It would be ideal to store email settings in appsettings or config file and then load this using configuration to prevent hardcoding the settings in your source code :grin: I believe you have covered this topic in previous projects

2024-03-28 17:36 UTC, kimfom01 commented on SportsResultNotifier.kronyer/SportsResultNotifier/MailService.cs
> +                string body = $@"
I want you to learn about and use the [StringBuilder](https://learn.microsoft.com/en-us/dotnet/api/system.text.stringbuilder?view=net-8.0) class to build the email body as performing repeated modifications to a string has negative performance impacts.
Here's is what [Microsoft Docs](https://learn.microsoft.com/en-us/dotnet/standard/base-types/stringbuilder) has to say about this situation
![image](https://github.com/TheCSharpAcademy/CodeReviews.Console.SportsResults/assets/57032138/b55e490c-0e93-4e4d-8833-2ce7af41c06c)

2024-03-28 17:36 UTC, kimfom01 commented on SportsResultNotifier.kronyer/SportsResultNotifier/MailService.cs
> +{
Don't forget about filescoped namespaces :sweat_smile:

2024-03-28 17:36 UTC, kimfom01 commented on SportsResultNotifier.kronyer/SportsResultNotifier/MailService.cs
> +                using (MailMessage mail = new MailMessage())
This one is just for reducing nesting :grin: 

From
```cs
using (MailMessage mail = new MailMessage())
{
    // Your code
}
```
To 
```cs
using MailMessage mail = new MailMessage();
// Your code
```
also you can do same for the SmtpClient below

PS: notice the removal of `()`. `{}` and inclusion of `;`

2024-04-06 08:09 UTC, TheCSharpAcademy commented
@kronyer Let us know if you need help 🤓

2024-04-17 21:29 UTC, kronyer commented
I stopped coding for a month for working reasons. So I'm back now. Hope I did everything as asked!

2024-04-18 07:30 UTC, kimfom01 commented
> I stopped coding for a month for working reasons. So I'm back now. Hope I did everything as asked!

Welcome back!

2024-04-18 09:49 UTC, kimfom01 commented
> I stopped coding for a month for working reasons. So I'm back now. Hope I did everything as asked!

Yeah everything looks good now I will approve it

2024-04-18 09:49 UTC, kimfom01 approved these changes

2024-04-18 10:52 UTC, merged