Project finished
the-csharp-academy/CodeReviews.Console.SportsResults pull request #47
Opened 2024-12-10 01:47 UTC by jollejonas

Project finished. Looking forward to your review 😄

2024-12-17 12:10 UTC, chrisjamiecarter requested changes
Hey @jollejonas 👋,

Excellent work on your SportsResults project submission 🎉!

I have performed a peer review. Review/ignore as you wish.

***

🔴 Can you provide the `appsettings.json` file?

![image](https://github.com/user-attachments/assets/c183d79e-2cfc-4ba0-9cb1-37e7e80e74be)

🔴 Where is the implementation of the once per day requirement?

![image](https://github.com/user-attachments/assets/fd270484-6121-440f-964e-beb32e1f7a83)

Please revisit to try understand and fix these issues 🔧 , as they relate to the projects requirements and they block my approval.

***

Feel free to reach out if you have any questions or if you'd like to collaborate further on any of these points 🆘 .

I will go ahead and wait for you to make your changes, commit and push (which will then notify me) 😊 !

Thanks,
@chrisjamiecarter 👍

2024-12-17 20:58 UTC, jollejonas commented
Thanks a lot for the review.

I have the password for my Smtp settings in the appsettings.json file, that is why it is not uploaded.
Should i remove the password or store my password in another way? 😄

2024-12-17 21:03 UTC, chrisjamiecarter commented
@jollejonas - that is a valid reason!

But, normally you would include a template version, with the sensitive info redacted/dummified.

Otherwise I have to do a bunch of detective work to figure out what I need to put into a appsettings.json just to get it to run.

i.e.,
`appsettings.json`
```
{
   "mailUsername": "YourMailUsername",
   "mailPassword": "YourMailPassword"
}
```

Thanks,
@chrisjamiecarter 👍

2024-12-18 16:17 UTC, chrisjamiecarter approved these changes
Hey @jollejonas 👋 ,

Excellent job getting your updates pushed through, 💪 , you now fulfill all the requirements.

One thing, remember to do this:
![image](https://github.com/user-attachments/assets/4a9717f4-71b4-4be7-9f8f-b01f17789d08)

So your appsettings get copied to the output directory.

***

I will go ahead and mark as approved, keep up the excellent work on the next projects! 😊

Best regards,
@chrisjamiecarter 👍

2025-09-17 21:18 UTC, closed without merging